source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'LiangTools_Example' do
  pod 'LiangTools', :path => '../'

  target 'LiangTools_Tests' do
    inherit! :search_paths

    
  end
end
